JuliaIO/JLD.jl

- src/JLD.jl
Tests pass on 0.3 for me. On 0.4, the unit tests hang on current master with and without this commit.
In my own code, this commit works, and silences the deprecation warning.
> fix deprecation warning

- src/JLD.jl
- src/jld_types.jl
- test/custom_serialization.jl
- test/runtests.jl
- test/type_translation.jl
This is a revival of https://github.com/timholy/HDF5.jl/pull/191. To fix types that have changed between writing and the current code, it uses the following strategy:
1. The user defines a `MyOldType` that corresponds to the on-disk version
2. The user specifies that one should read an object whose *string* type is `MyType` as `MyOldType`
3. The user define a `readas` method to convert a `MyOldType` into `MyType`.
> readas, writeas, and translate for custom serialization & type-repair

- .gitignore
- .travis.yml
- README.md
The shenanigans we used to pull with `workspace` now seem to be failing
due to precompilation. OTOH, now that we can merge Coverage counts
from multiple julia processes, we don't need those shenanigans anymore.
This also seems to fix a previously-undetected problem, that the
DataFrames test wasn't being run (test/REQUIRE doesn't get used if you're
not running with `Pkg.test`).
Hopefully fixes problems noted in #16. CC @amack315.
> Fix Travis error due to precompilation

- src/JLD.jl
- test/jldtests.jl
Fixes a former stack overflow (from the Colon translation calls).
> Hyperslab addition (`dset[indexes...] = x::Number`)

- REQUIRE
- src/JLD.jl
This prevents naming conflicts with other packages that use FileIO
> Base load/save on FileIO

- doc/jld.md
- src/JLD.jl
- test/jldtests.jl
When compression is used, then by default `JLD` creates HDF5 that are not portable since they require the Blosc library to be read. This adds a new flag `compatible=true` that can be used in addition to `compress=true` that uses the "deflate" algorithm and avoids the Blosc library.
> Implement `compatible=true` flag to create portable HDF5 files

- src/JLD.jl
- test/jldtests.jl
I was playing with [BaseBenchmarks.jl](https://github.com/JuliaCI/BaseBenchmarks.jl) on my own machine, and discovered that JLD doesn't support symbols that have a space in them, constructed via `symbol("hello there")`. This fixes that problem.
I also turned off the function tests for julia-0.5, see #57.
> Escape spaces in symbols

- .travis.yml
- REQUIRE
- appveyor.yml
- src/JLD.jl
- src/JLD00.jl
- src/jld_types.jl
- test/jldtests.jl
julia-0.5 issues a warning when functions are redefined, and this caught a bug in the former implementation that affects all versions of julia.
> Update for 0.5 deprecations

- src/JLD.jl
- src/jld_types.jl
- test/jldtests.jl
I'm not sure I see a more elegant solution for the parser deprecation warning.
> Fix more julia-0.5 deprecations

- REQUIRE
- src/JLD.jl
- src/JLD00.jl
- src/jld_types.jl
- test/jldtests.jl
UTF16String was removed from Base in Julia 0.5.
> Use LegacyStrings to support UFT16String

- .travis.yml
- appveyor.yml
- src/JLD.jl
- src/JLD00.jl
- test/jldtests.jl
For https://github.com/JuliaLang/julia/pull/18362
I also need to add an `rm(fn)` otherwise HDF5 1.10 gives an error.
Also enable travis on 0.5.
> Use isassigned(::Array) instead of isdefined(::Array)

- src/JLD.jl
- src/jld_types.jl
https://github.com/JuliaLang/julia/pull/17057 doesn't support `@eval`, but I want to be able to run BaseBenchmarks on it. So this replaces all of the `@eval` functions with their roughly equivalent `@generated` functions.
> make this package JuliaLang/julia#265 ready

- src/JLD00.jl
Write 'Dict{String => Any}' instead of '(String => Any)'.
Use 'unsafe_string' instead of 'bytestring'.
> Fix deprecated warnings.

- src/JLD.jl
...since input types might not exist in `current_module()`. This fixes using a function which calls `JLD.translate` inside a module scope where `JLD` is not imported (but the caller does have `JLD` imported). This bug can be seen in the `SerializationTests` failure [here](https://github.com/JuliaCI/BenchmarkTools.jl/pull/23).
I'm not sure whether this PR is really the correct fix for this issue - it might violate existing assumptions or rely on bad assumptions. For example, this fix may be broken if `e` is not fully qualified.
Credit to @maleadt for hunting this down.
> eval julia_type input in Main instead of current_module()

- src/JLD.jl
- src/jld_types.jl
- test/jldtests.jl
This allows tests to pass on the jb/subtype branch, along with updates to HDF5 and Compat. ~~I used `VERSION >= v"0.6.0-dev"` as the version check for now.~~ Now uses feature-based testing; should be non-breaking.
> update for jb/subtype

- src/JLD.jl
- src/JLD00.jl
- src/datafile.jl
- src/jld_types.jl
- test/custom_serialization.jl
- test/jldtests.jl
I did this with a quick regex, so this should definitely be skimmed before merging
ref JuliaLang/julia#19989
> Array(T, dims...) to Array{T}(dims...) (ref JuliaLang/julia#19989)

- src/JLD.jl
- test/jldtests.jl
by nulling the `MethodInstance`/`LambdaInfo` field. This is useful for storing profile output.
> Add support for StackFrames

- REQUIRE
- src/jld_types.jl
- test/jldtests.jl
~~**DO NOT MERGE NOW!!!!**~~
~~This requires https://github.com/JuliaLang/Compat.jl/pull/325 and a new tag. I'm using this (and other) PR's to check if the implementation is correct.~~
Ready now.
> Fix 0.6 abstract and primitive type declaration depwarn

- doc/jld.md
hdf5.md no longer in this repo. See commit: https://github.com/JuliaIO/JLD.jl/commit/faf41bfc96bc3ba0acaad0fde79ea3dca9b6c677
> Memory Map link to hdf5 package

- src/JLD.jl
This change should be merged and tagged in a release before
https://github.com/JuliaLang/julia/pull/21057 renames Core.BottomType
> replace Core.BottomType => typeof(Union{})

- test/jldtests.jl
I don't have a 32 bit installation so I'm now sure if this works. Let's see what AppVeyor says.
> Adjust test of StackFrame serialization to work on 32 bit platforms

- .travis.yml
- README.md
- REQUIRE
- appveyor.yml
- src/JLD.jl
- src/JLD00.jl
- src/datafile.jl
- src/jld_types.jl
- test/JLDTest.jl
- test/custom_serialization.jl
- test/jldtests.jl
- test/type_translation.jl
Much easier to maintain than trying to support 0.4, 0.5, 0.6, and 0.7 all at once. Plus some 0.7 depwarns require at least 0.6 to silence.
> Bump minimum Julia version to 0.6

- LICENSE.txt
- REQUIRE
- src/JLD.jl
- src/JLD00.jl
- src/jld_types.jl
- test/jldtests.jl
- test/type_translation.jl
since calling `pointer()` explicitly discards gc-rooting
need to ensure that there is a memory barrier that uses the value
after we know for certain we are done with the value
> fix missing gc-roots

- src/JLD.jl
As of https://github.com/JuliaLang/julia/pull/23579, packages aren't loaded into Main by default, which breaks one of the checks we're using here in `addrequire`. This PR fixes that by adding an additional check for whether the given module is a root module.
See also discussion in https://github.com/JuliaLang/julia/commit/ff9fb483172ad792c47b7652eff1173044f3b9ae, and cc @KristofferC.
> Fix for packages not loaded into Main on 0.7

- doc/jld.md
I added some additional notes to the [Rescuing Old Types](https://github.com/JuliaIO/JLD.jl/blob/master/doc/jld.md#rescuing-old-types) section of the documentation about using `translate`. Addresses #180.
> Clarify use of translate in documentation

- .travis.yml
- REQUIRE
- appveyor.yml
- src/JLD.jl
- src/JLD00.jl
- src/datafile.jl
- src/jld_types.jl
- test/custom_serialization.jl
- test/jld_dataframe.jl
- test/jldtests.jl
- test/require.jl
- test/runtests.jl
- test/type_translation.jl
As far as I can tell, I caught everything (at least, tests pass and I'm getting no warnings). This is a combination of #217 and #215, along with the remaining changes.
By the way, this drops support for versions < 0.7, which seems important to mention.
> Fix all julia 0.7 issues

- src/JLD00.jl
A simple refactor based on the [style guide](https://docs.julialang.org/en/v1/manual/style-guide/#Do-not-write-x-f(x)-1).
> refactor: simplify map call

- doc/jld.md
Could be useful to show how to retrieve the names of the dataset in some jld files without loading the entire dataset in memory and looking at the dictionnary keys.
> Use of the names function in the documentation

- .travis.yml
- README.md
In preparation for the removal of JLDArchives from the registry. (I don't think it needs to be registered.)
Fixes https://github.com/JuliaIO/JLDArchives.jl/issues/18
> Use URL to access JLDArchives

- .gitignore
- .travis.yml
- Project.toml
- src/JLD.jl
- src/JLD00.jl
- src/jld_types.jl
- test/custom_serialization.jl
- test/jld_dataframe.jl
- test/jldtests.jl
- test/require.jl
- test/type_translation.jl
LegacyStrings has never been released with a Project.toml. This removes it from the package, but with a cost: no support for UTF-16 strings. The fact that LegacyStrings has never been updated might be a sign that it is not in high demand.
This also removes the dependency on Compat, and modernizes some elements of the package.
> Ditch Compat, LegacyStrings

- src/JLD.jl
> Fix some issues with @save and @load

- src/jld_types.jl
Fix for the issue [#235](https://github.com/JuliaIO/JLD.jl/issues/235)
> Issue #235: reconstructing type with non-ascii attribute names

- src/JLD.jl
In preparation for proposed JuliaIO/HDF5.jl#776, use the low-level `h5d_create` method directly. HDF5's mid-level API (`dataset_create`) is designed around setting properties as keyword-value pairs, but given the existing infrastructure which uses `HDF5.Properties` directly, drop down to using the low-level calls instead.
>  Directly call low-level h5d_create when using HDF5.Properties

- src/jld_types.jl
- test/jldtests.jl
As the code comment says, there seems to be some subtlety in how HDF5 datatypes compare equal or not based on whether the datatype has been committed to the file and loaded or not. This seems to be a change with libhdf5 v1.12 (since prior HDF5 versions seemed to work fine), but I haven't found any clarifications in documentation about whether this is expected behavior or not.
In preparing for the HDF5 v0.14 release, we'd discovered part of this issue and were already trying to copy one of the types in the comparison, but it was an insufficient patch. As best as I can tell, the caching of datatypes means that for nested data types, there can be committed vs transient comparisons made at almost any depth, so the easiest thing to do is to just copy both loaded and reconstructed types for …
> Fix #294, #297 - comparing HDF5 datatypes is sensitive to committed history

- Project.toml
- src/JLD.jl
- src/JLD00.jl
- src/jld_types.jl
`T.mutable` no longer exists of https://github.com/JuliaLang/julia/pull/41018 (Julia 1.7)
Use new `ismutabletype` instead. Create a backwards compatible shim for Julia < 1.7 for `ismutabletype`.
> Use ismutabletype(T) for datatypes

- Project.toml
- src/JLD.jl
@musm, We probably should have added the H5Zblosc dependency in 0.12.4 because dropping Blosc support is breaking for JLD.jl.
> [urgent-fix-breakage] JLD depends on H5Zblosc

- Project.toml
- src/JLD.jl
- Revert "[urgent-fix-breakage] JLD depends on H5Zblosc (#305)"
- Revert "Update Project.toml"
- Intermediary fixup release
> Intermediary fixup release to mitigate HDF5 v0.16 issues

- src/JLD.jl
- src/jld_types.jl
HDF5.exists was removed in v0.16 of HDF5 and since the present version of JLD specifies this as minimum compatible HDF5 version, it is safe to remove the warning.
Also update HDF5.haddr_t and HDF5 deprecated calls
fix https://github.com/JuliaIO/JLD.jl/issues/323 https://github.com/JuliaIO/JLD.jl/issues/324
> Fix HDF5.exists, HDF5.haddr_t, and HDF5.object_info deprecation warnings

- Project.toml
- src/JLD.jl
https://github.com/JuliaIO/HDF5.jl/pull/1104 removed HDF5._dataspace which JLD.jl still used until this pull request.
> Fix use of HDF5._dataspace
