.travis.yml, README.md, appveyor.yml
This is the simple part of #4, after merging #5
=> Improve scripts for CI testing

README.md, doc/jld.md, src/JLD.jl, src/JLD00.jl, test/JLDTest.jl, test/require.jl
This fixes a deprecation warning but also just seems cleaner to me.
=> Clean up `addrequire`

src/JLD.jl, test/jldtests.jl
This pull request resolves #11 by adding serialization for anonymous functions via lowered ast expressions.
=> Serialize anonymous functions (fixes #11)

REQUIRE, src/JLD.jl, src/JLD00.jl, src/jld_types.jl, test/jldtests.jl
=> Fix type deprecations

src/JLD.jl, src/JLD00.jl, src/jld_types.jl, test/jldtests.jl, test/runtests.jl
Let's see if I understand how it works correctly....
=> Union() -> Union{}

src/JLD.jl, test/jldtests.jl
Migrates https://github.com/JuliaLang/HDF5.jl/pull/214 here to JLD.
=> Record creator information

README.md
=> document a subtlety of transitioning to FileIO.save

src/JLD.jl, test/jldtests.jl
The fix can't be ideal without JuliaLang/julia#14472, but this should be an improvement.
CC @mweastwood
=> Prevent stack overflow with FileIO interface (fix #46)

REQUIRE, src/JLD.jl, src/jld_types.jl, test/jldtests.jl
Fixes the deprecation warnings.
=> Deprecations fix

src/JLD.jl
hopefully should work everywhere without being deprecated
=> WIP: try a Dict constructor from an array of Tuples

src/JLD.jl, test/jldtests.jl
`@load` was untested, broken on 0.5, and was putting all variables into the global scope.
While I still permit `@load "fname.jld"`, I have deprecated the functionality where if you did `@load x` and x was an Expr, JLD would call eval in the calling module. This may have been somewhat useful for interactive use, but it wouldn't do the right thing inside a function, and it never worked for the more obvious case where `x` was a symbol so it's not clear to me that anyone ever used it.
Should fix #85
=> Improve load macro

src/JLD.jl
* Use tuple type instead of tuples (Ref https://github.com/JuliaLang/julia/pull/18444 and it's easier to infer in general)
=> Fix use of `invoke`

src/JLD.jl, src/JLD00.jl, src/datafile.jl, src/jld_types.jl, test/jldtests.jl
...and remove 0.4-dev special cases since 0.4 is now required
=> Use take! instead of takebuf_string

src/JLD.jl, src/JLD00.jl
Fix for jb/fasterstring branch. Should work with julia >= 0.4.
=> don't access String .data field

src/JLD.jl, test/jldtests.jl
this uses a unique syntax for 'where' so that parsing it is backwards compatible with loading on v0.5 (and isn't ambiguous for parsing on v0.6)
=> attempt a better update for jb/subtype

README.md
=> Warning note about JLD security

test/jldtests.jl
Ref end comments at https://github.com/JuliaIO/JLD.jl/pull/145#issuecomment-291193343
=> Fix StackFrame test

test/jldtests.jl
=> Add a test for issue 173

REQUIRE, src/JLD.jl, src/JLD00.jl, src/jld_types.jl, test/custom_serialization.jl, test/jldtests.jl, test/runtests.jl
=> Fix most 0.7 depwarn and errors

src/JLD.jl, src/JLD00.jl
@ararslan see if this fixed the nansoldier issue. Unfortunately JLD fails tests on 0.7 independent of this issue.
=> Adjust to reinterpret change

test/custom_serialization.jl, test/jld_dataframe.jl, test/jldtests.jl, test/type_translation.jl
Otherwise you run into trouble if two people simultaneously run JLD tests on the same machine.
=> Make sure to use a unique filename in JLD test

src/JLD.jl, src/jld_types.jl, test/jldtests.jl
The PR failed tests but it passes locally for me when merged, so try rebasing on master.
=> fix reading booleans

src/JLD.jl, test/jldtests.jl
=> Stop extending FileIO methods

Project.toml, src/JLD.jl
- Add HDF5 v0.16 compatibility (#305)
- Bump JLD version
=> Update to accommodate HDF5 v0.16
